### ISSUE TITLE
The plugin is not compiled?

### ISSUE THREAD

**Issue by Elguerrero11** [567legodude/SuperMaps#1]
If it is not compiled I can not use it, please compile it and I advise you to put it in spigot.

**Comment by 567legodude** [comment]
This plugin was effectively abandoned, I never intended to put it on spigot because there are already better map APIs.
I assume you are referencing the dependency requirement of the SSecurity plugin. It should be noted that this plugin comes bundled pre-compiled in a .zip when you download that plugin.

**Comment by Elguerrero11** [comment]
O.O, it's true, I did not realize, well in that case I feel the discomfort, thanks for everything and have a good day
